# Generated by Django 5.0.4 on 2024-05-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
